[package]
name = "pharmakon-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
pharmakon-core.workspace = true
pharmakon-common.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
log.workspace = true
futures.workspace = true
tokio-cron-scheduler.workspace = true
serde_json.workspace = true
rand.workspace = true
dirs.workspace = true
tracing.workspace = true
tower-http = { workspace = true, features = ["fs", "cors", "trace", "compression-full", "set-header"] }
sysinfo = "0.38.4"
teloxide.workspace = true
serenity.workspace = true
slack-morphism.workspace = true
uuid.workspace = true
egui = "0.31"
eframe = "0.31"
tray-icon = "0.19"
muda = "0.15"
rfd = "0.15"
pharmakon-tools = { path = "../tools" }
async-trait.workspace = true
chrono.workspace = true
