//! World Model Agent — Simulate-before-acting execution loop.
//!
//! Replaces reactive CodeAct retry loops with:
//!   1. Generate 3-5 candidate plans (LLM)
//!   2. Simulate each in isolated temp workspace (MCTS + cargo check)
//!   3. Score plans by success probability, token cost, EVPI
//!   4. Commit best plan atomically (SnapshotStore checkpoint)
//!   5. On failure: rollback_to_event() → try next plan
//!
//! Activated for Deep tasks; Simple/Standard tasks skip to standard CodeAct.

use crate::agent::Agent;
use crate::model::{CompletionRequest, Message, MessageContent};
use crate::orchestration::cognitive_economics::EvpiEstimator;
use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

// ═══════════════════════════════════════════════════════
// Plan Types
// ═══════════════════════════════════════════════════════

/// A candidate action plan generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidatePlan {
    pub id: String,
    /// Human-readable description of the approach.
    pub description: String,
    /// Estimated token cost for this plan.
    #[serde(default)]
    pub estimated_tokens: u64,
    /// Steps to execute (CodeAct scripts or tool calls).
    pub steps: Vec<PlanStep>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    /// Tool name to invoke (e.g., "codeact", "write_file", "shell").
    pub tool: String,
    /// Arguments for the tool.
    pub args: serde_json::Value,
    /// Dependencies on previous step indices (for ParallelExecutor).
    #[serde(default)]
    pub depends_on: Vec<usize>,
    /// Dry-run first for destructive operations.
    #[serde(default)]
    pub dry_run_first: bool,
}

/// Validation and scoring result for a plan after simulation.
#[derive(Debug, Clone)]
pub struct PlanValidation {
    pub plan_id: String,
    pub valid: bool,
    pub issues: Vec<String>,
    /// Score 0.0–1.0: estimated success probability.
    pub mcts_score: f64,
    /// Estimated token cost from simulation.
    pub token_cost: u64,
    /// EVPI: expected value of new information from executing this plan.
    pub evpi: f64,
}

// ═══════════════════════════════════════════════════════
// Plan Generation
// ═══════════════════════════════════════════════════════

/// Generate 3-5 candidate plans from an LLM.
pub async fn generate_candidate_plans(
    agent: &Agent,
    task: &str,
    context: &str,
    max_plans: usize,
) -> Result<Vec<CandidatePlan>> {
    let tool_list = {
        let reg = agent.registry.lock().await;
        let metadata = reg.all_metadata();
        metadata.iter()
            .filter(|m| m.category == pharmakon_common::ToolCategory::Core)
            .map(|m| format!("- {}: {}", m.name, m.description))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let prompt = format!(
        r#"You are a strategic planner for an autonomous coding agent. Given the task below, generate {max_plans} candidate action plans.

Each plan should have concrete steps using the available tools. Output valid JSON only.

Available tools:
{tool_list}

Task: {task}

Context: {context}

Output format:
```json
[
  {{
    "id": "plan-1",
    "description": "Brief approach description",
    "estimated_tokens": 500,
    "steps": [
      {{
        "tool": "codeact",
        "args": {{"script": "..."}},
        "depends_on": [],
        "dry_run_first": false
      }}
    ]
  }}
]
```

Rules:
- Steps execute in order unless depends_on specifies otherwise
- Mark destructive steps (rm, git push) with dry_run_first: true
- Use direct tools (shell, write_file, read_file, grep_files) for single operations. DO NOT wrap single commands in codeact. Only use codeact for genuinely compound file/code work (3+ sequential tool calls on the same file set, e.g. grep→filter→write). If a task can be done with one shell command, use shell.
- Each plan should be a distinct strategy, not variations of the same idea
- estimated_tokens: your rough guess of API token cost for this plan

Reply with ONLY the JSON array, no explanation."#,
        max_plans = max_plans.max(3).min(5),
        tool_list = tool_list,
        task = task,
        context = context,
    );

    let model = {
        let m = agent.model.lock().await;
        (*m).clone()
    };

    let request = CompletionRequest {
        messages: vec![Message {
            role: "user".to_string(),
            content: Some(MessageContent::Text(prompt)),
            ..Default::default()
        }],
        temperature: Some(0.3),
        max_tokens: Some(2048),
        tools: None,
    };

    let response = model.complete(request).await.map_err(|e| anyhow!("Plan generation failed: {}", e))?;
    let text = response.content.as_ref()
        .and_then(|c| c.as_text())
        .ok_or_else(|| anyhow!("Empty response from planner"))?;

    // Extract JSON from code block if present
    let json_text = if let Some(start) = text.find("```json") {
        let inner = &text[start + 7..];
        if let Some(end) = inner.find("```") {
            &inner[..end]
        } else { inner }
    } else if let Some(start) = text.find('[') {
        &text[start..]
    } else {
        text
    };

    let plans: Vec<CandidatePlan> = serde_json::from_str(json_text.trim())
        .map_err(|e| anyhow!("Failed to parse plans: {}. Raw: {}", e, &json_text[..json_text.len().min(200)]))?;

    if plans.is_empty() {
        return Err(anyhow!("Zero plans generated"));
    }

    log::info!(
        "WorldModel: generated {} plans for task '{}'",
        plans.len(),
        &task[..task.len().min(60)]
    );

    Ok(plans)
}

// ═══════════════════════════════════════════════════════
// Simulation Engine
// ═══════════════════════════════════════════════════════

/// Simulate a single plan in an isolated temp workspace.
/// Returns PlanValidation with scores.
pub async fn simulate_plan(
    _agent: &Agent,
    plan: &CandidatePlan,
    workspace_root: &Path,
) -> Result<PlanValidation> {
    let start = std::time::Instant::now();
    let temp_dir = tempfile::tempdir()?;
    let sim_root = temp_dir.path();

    log::info!("WorldModel: simulating plan '{}'", plan.id);

    // 1. Copy workspace to temp dir (skip heavy dirs)
    copy_workspace_lightweight(workspace_root, sim_root).await?;

    // 2. Execute steps sequentially (respecting depends_on)
    let mut step_results: Vec<bool> = vec![false; plan.steps.len()];
    let mut issues = Vec::new();

    for (i, step) in plan.steps.iter().enumerate() {
        // Check dependencies
        let deps_ok = step.depends_on.iter().all(|&dep_idx| {
            dep_idx < i && step_results.get(dep_idx).copied().unwrap_or(false)
        });
        if !deps_ok {
            issues.push(format!("Step {} has unmet dependencies", i));
            continue;
        }

        let success = match step.tool.as_str() {
            "codeact" => {
                execute_codeact_in_dir(sim_root, step.args.get("script")
                    .and_then(|s| s.as_str())
                    .unwrap_or(""))
                    .await
                    .is_ok()
            }
            "shell" => {
                execute_shell_in_dir(sim_root, step.args.get("command")
                    .and_then(|s| s.as_str())
                    .unwrap_or(""))
                    .await
                    .is_ok()
            }
            "write_file" => {
                let path = step.args.get("path").and_then(|s| s.as_str()).unwrap_or("");
                let content = step.args.get("content").and_then(|s| s.as_str()).unwrap_or("");
                let resolved = resolve_path(sim_root, path);
                tokio::fs::create_dir_all(resolved.parent().unwrap_or(Path::new("."))).await.ok();
                tokio::fs::write(&resolved, content).await.is_ok()
            }
            "apply_patch" => {
                let path = step.args.get("path").and_then(|s| s.as_str()).unwrap_or("");
                let patch = step.args.get("patch").and_then(|s| s.as_str()).unwrap_or("");
                apply_patch_in_dir(sim_root, path, patch).await
            }
            _ => {
                // Unknown tool in simulation — skip
                log::debug!("WorldModel: skipping unknown tool '{}' in simulation", step.tool);
                true
            }
        };

        step_results[i] = success;
        if !success {
            issues.push(format!("Step {} ({}) failed", i, step.tool));
        }
    }

    // 3. Run cargo check
    let cargo_ok = run_cargo_check(sim_root).await;
    if !cargo_ok {
        issues.push("cargo check failed in simulation".to_string());
    }

    // 4. Score
    let all_steps_ok = step_results.iter().all(|&r| r);
    let mcts_score = score_plan(all_steps_ok, cargo_ok, plan.estimated_tokens);

    let evpi_estimator = EvpiEstimator::new(
        0.5, // moderate genome similarity (new plan)
        0.7, // deep task complexity
        0.8, // cached success rate
    );

    let elapsed = start.elapsed().as_millis();
    log::info!(
        "WorldModel: plan '{}' scored {:.3} (steps_ok={}, cargo_ok={}, {}ms)",
        plan.id, mcts_score, all_steps_ok, cargo_ok, elapsed
    );

    Ok(PlanValidation {
        plan_id: plan.id.clone(),
        valid: all_steps_ok && cargo_ok,
        issues,
        mcts_score,
        token_cost: plan.estimated_tokens,
        evpi: evpi_estimator.evpi(),
    })
}

fn score_plan(steps_ok: bool, cargo_ok: bool, estimated_tokens: u64) -> f64 {
    let step_score = if steps_ok { 0.4 } else { 0.0 };
    let cargo_score = if cargo_ok { 0.4 } else { 0.0 };
    // Token efficiency: cheaper plans score higher
    let token_score = if estimated_tokens > 0 {
        (0.2 * 2000.0 / estimated_tokens as f64).min(0.2)
    } else { 0.1 };
    step_score + cargo_score + token_score
}

// ═══════════════════════════════════════════════════════
// Commit & Rollback Loop
// ═══════════════════════════════════════════════════════

/// Main World Model execution: generate → simulate → commit → verify → rollback on failure.
pub async fn execute_world_model(
    agent: &Agent,
    _session_id: &str,
    task: &str,
) -> Result<String> {
    let workspace_root = std::env::current_dir().unwrap_or_default();

    // Phase 1: Generate candidate plans
    let plans = generate_candidate_plans(agent, task, "", 4).await?;

    // Phase 2: Simulate all plans in parallel
    let sim_futures: Vec<_> = plans.iter().map(|plan| {
        simulate_plan(agent, plan, &workspace_root)
    }).collect();

    let sim_results: Vec<Result<PlanValidation>> = futures::future::join_all(sim_futures).await;

    // Collect validations, sort by score
    let mut validations: Vec<(usize, PlanValidation)> = sim_results.into_iter()
        .enumerate()
        .filter_map(|(i, r)| r.ok().map(|v| (i, v)))
        .collect();

    validations.sort_by(|a, b| b.1.mcts_score.partial_cmp(&a.1.mcts_score).unwrap_or(std::cmp::Ordering::Equal));

    if validations.is_empty() {
        return Err(anyhow!("All plan simulations failed"));
    }

    log::info!(
        "WorldModel: best plan '{}' with score {:.3}. {} candidates simulated.",
        validations[0].1.plan_id,
        validations[0].1.mcts_score,
        validations.len()
    );

    // Phase 3: Commit best plan, fall through on failure
    for (idx, _validation) in &validations {
        let plan = &plans[*idx];

        // Record event_id for rollback checkpoint
        let _checkpoint_id = format!("world_model_{}_{}", plan.id, uuid::Uuid::new_v4().to_string().chars().take(8).collect::<String>());

        // Snapshot files the plan touches
        let mut snapshotted_files: Vec<(PathBuf, String)> = Vec::new();
        for step in &plan.steps {
            if step.tool == "write_file" || step.tool == "apply_patch" {
                if let Some(path_str) = step.args.get("path").and_then(|s| s.as_str()) {
                    let resolved = resolve_path(&workspace_root, path_str);
                    if resolved.exists() {
                        if let Ok(snap_id) = agent.snapshot_store.snapshot_file(&resolved).await {
                            snapshotted_files.push((resolved, snap_id));
                        }
                    }
                }
            }
        }

        // Execute plan steps
        let mut all_ok = true;
        for step in &plan.steps {
            let result = match step.tool.as_str() {
                "codeact" => {
                    let engine = crate::orchestration::codeact::CodeActEngine::new(workspace_root.clone());
                    let script = step.args.get("script").and_then(|s| s.as_str()).unwrap_or("");
                    let r = engine.execute(script);
                    if r.success { Ok(r.output) } else { Err(anyhow!(r.error.unwrap_or_default())) }
                }
                "shell" => {
                    let cmd = step.args.get("command").and_then(|s| s.as_str()).unwrap_or("");
                    let output = tokio::process::Command::new("sh").arg("-c").arg(cmd)
                        .output().await
                        .map_err(|e| anyhow!("shell failed: {}", e))?;
                    if output.status.success() {
                        Ok(String::from_utf8_lossy(&output.stdout).to_string())
                    } else {
                        Err(anyhow!("shell failed: {}", String::from_utf8_lossy(&output.stderr)))
                    }
                }
                _ => {
                    // Delegate to agent's tool registry
                    let mut reg = agent.registry.lock().await;
                    match reg.hydrate(&step.tool) {
                        Some(tool) => {
                            tool.call(step.args.clone()).await
                                .map_err(|e| anyhow!("{}", e.0))
                        }
                        None => Err(anyhow!("Tool not found: {}", step.tool)),
                    }
                }
            };

            if let Err(e) = result {
                log::warn!("WorldModel: plan '{}' step '{}' failed: {}", plan.id, step.tool, e);
                all_ok = false;
                break;
            }
        }

        if all_ok {
            // Run RLFC validation
            if run_cargo_check(&workspace_root).await {
                log::info!("WorldModel: plan '{}' committed and validated successfully", plan.id);
                return Ok(format!(
                    "✅ Plan '{}' executed successfully ({})",
                    plan.id, plan.description
                ));
            }
        }

        // Rollback on failure
        log::warn!("WorldModel: rolling back plan '{}'", plan.id);
        for (path, snap_id) in &snapshotted_files {
            if let Err(e) = agent.snapshot_store.restore(snap_id, path).await {
                log::error!("WorldModel: rollback failed for {}: {}", path.display(), e);
            }
        }
    }

    Err(anyhow!("All {} candidate plans failed. Last plan: {:?}",
        validations.len(),
        validations.last().map(|v| &v.1.plan_id)
    ))
}

// ═══════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════

async fn copy_workspace_lightweight(from: &Path, to: &Path) -> Result<()> {
    let skip_dirs = ["target", ".git", ".pharmakon", "node_modules", ".fastembed_cache"];
    let mut entries = tokio::fs::read_dir(from).await?;
    while let Some(entry) = entries.next_entry().await? {
        let path = entry.path();
        let dest = to.join(entry.file_name());
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if path.is_dir() {
            if skip_dirs.contains(&name_str.as_ref()) { continue; }
            if name_str.starts_with('.') && name_str != ".cargo" { continue; }
            tokio::fs::create_dir_all(&dest).await?;
            Box::pin(copy_workspace_lightweight(&path, &dest)).await?;
        } else if path.is_file() {
            tokio::fs::copy(&path, &dest).await?;
        }
    }
    Ok(())
}

async fn execute_codeact_in_dir(dir: &Path, script: &str) -> Result<String> {
    let engine = crate::orchestration::codeact::CodeActEngine::new(dir.to_path_buf());
    let result = engine.execute(script);
    if result.success { Ok(result.output) }
    else { Err(anyhow!(result.error.unwrap_or_default())) }
}

async fn execute_shell_in_dir(dir: &Path, cmd: &str) -> Result<String> {
    let output = tokio::process::Command::new("sh")
        .arg("-c").arg(cmd)
        .current_dir(dir)
        .output().await
        .map_err(|e| anyhow!("shell: {}", e))?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(anyhow!("{}", String::from_utf8_lossy(&output.stderr)))
    }
}

async fn apply_patch_in_dir(dir: &Path, file_path: &str, patch_text: &str) -> bool {
    let resolved = resolve_path(dir, file_path);
    let Ok(original) = tokio::fs::read_to_string(&resolved).await else { return false; };
    let Ok(patch) = diffy::Patch::from_str(patch_text) else { return false; };
    let Ok(patched) = diffy::apply(&original, &patch) else { return false; };
    tokio::fs::write(&resolved, patched).await.is_ok()
}

async fn run_cargo_check(dir: &Path) -> bool {
    tokio::process::Command::new("cargo")
        .arg("check")
        .current_dir(dir)
        .output()
        .await
        .map(|o| o.status.success())
        .unwrap_or(false)
}

async fn run_rlfc_validation(dir: &Path) -> Result<()> {
    let output = tokio::process::Command::new("cargo")
        .arg("check")
        .current_dir(dir)
        .output()
        .await
        .map_err(|e| anyhow!("cargo check: {}", e))?;

    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(anyhow!("validation failed: {}", &stderr[..stderr.len().min(500)]))
    }
}

fn resolve_path(root: &Path, path: &str) -> PathBuf {
    let p = Path::new(path);
    if p.is_absolute() { p.to_path_buf() } else { root.join(p) }
}

// ═══════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_score_plan_perfect() {
        let s = score_plan(true, true, 1000);
        assert!(s > 0.8, "perfect plan should score > 0.8, got {}", s);
    }

    #[test]
    fn test_score_plan_failed() {
        let s = score_plan(false, false, 10000);
        assert!(s < 0.3, "failed plan should score < 0.3, got {}", s);
    }

    #[test]
    fn test_score_plan_cheaper_wins() {
        let cheap = score_plan(true, true, 500);
        let expensive = score_plan(true, true, 5000);
        assert!(cheap > expensive, "cheaper plan should score higher");
    }

    #[test]
    fn test_plan_serialization() {
        let plan = CandidatePlan {
            id: "test-1".into(),
            description: "Test plan".into(),
            estimated_tokens: 500,
            steps: vec![PlanStep {
                tool: "codeact".into(),
                args: serde_json::json!({"script": "print('hello')"}),
                depends_on: vec![],
                dry_run_first: false,
            }],
        };
        let json = serde_json::to_string(&plan).unwrap();
        let parsed: CandidatePlan = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, "test-1");
        assert_eq!(parsed.steps.len(), 1);
    }

    #[test]
    fn test_resolve_path() {
        let root = Path::new("/workspace");
        assert_eq!(resolve_path(root, "src/main.rs"), PathBuf::from("/workspace/src/main.rs"));
        assert_eq!(resolve_path(root, "/tmp/absolute.rs"), PathBuf::from("/tmp/absolute.rs"));
    }
}
