[package]
name = "pharmakon-core"
version = "0.1.0"
edition = "2024"

[dependencies]
pharmakon-common.workspace = true
pharmakon-memory.workspace = true
pharmakon-tools.workspace = true
pharmakon-mcp.workspace = true
bollard = "0.18.1"
serde.workspace = true
serde_json.workspace = true
notify.workspace = true
anyhow.workspace = true
async-trait.workspace = true
reqwest.workspace = true
tokio-cron-scheduler.workspace = true
qdrant-client.workspace = true
keyring.workspace = true
log.workspace = true
sqlx.workspace = true
futures.workspace = true
dirs.workspace = true
uuid.workspace = true
chrono.workspace = true
tokio.workspace = true
tiktoken-rs = "0.6"
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
lazy_static = "1.5"
regex = "1"
serde_yaml = "0.9"
once_cell = "1.x"
xcap.workspace = true
