[package]
name = "pharmakon-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
tokio-util = { version = "0.7.13", features = ["codec"] }
tower = { workspace = true }
